nelmio_cors:
    paths:
       "^/":
          allow_credentials: false
          origin_regex: false
          allow_origin: ['*']
          allow_headers: ['*']
          allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
          max_age: 3600
